[package]
name = "benchmark-games-rs"
version = "0.1.0"
authors = ["Prathmesh Prabhu <pprabhu@chromium.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
